from prettyconf import config

DEBUG = config('DEBUG', cast=config.boolean)

# MongoDB settings
MONGODB_URI = config('MONGODB_URI')
MONGODB_NAME = config('MONGODB_NAME')

# Scheduler settings
SCHEDULER_STORE_TYPE = config('SCHEDULER_STORE_TYPE')
SCHEDULER_MONGODB_COLLECTION = config('SCHEDULER_MONGODB_COLLECTION')
SCHEDULER_MAX_THREADS = config('SCHEDULER_MAX_THREADS', cast=int)
SCHEDULER_MAX_PROCESSES = config('SCHEDULER_MAX_PROCESSES', cast=int)
SCHEDULER_MAX_INSTANCES = config('SCHEDULER_MAX_INSTANCES', cast=int)
SCHEDULER_STREAM_UPDATE = config('SCHEDULER_STREAM_UPDATE', cast=int)
SCHEDULER_STREAM_VERIFY = config('SCHEDULER_STREAM_VERIFY', cast=int)
SCHEDULER_JOB_UPDATE_ID = 'job_update_streams'
SCHEDULER_JOB_VERIFY_ID = 'job_verify_streams'

# Default settings
DEFAULT_USER_AGENT = config('DEFAULT_USER_AGENT')
DEFAULT_STREAM_PRIORITY = {'FHD': 0, 'HD': 1, 'SD': 2}
DEFAULT_STREAM_QUALITY = 'SD'
DEFAULT_STREAM_UPDATE_DELAY = config('DEFAULT_STREAM_UPDATE_DELAY', cast=int)
DEFAULT_STREAM_UPDATE_TIMEOUT = config(
    'DEFAULT_STREAM_UPDATE_TIMEOUT', cast=int)
