version: "2"
services:
  scrapyd:
    container_name: scrapyd-streamerbot
    image: alexandresgf/scrapyd-service:latest
    environment:
      SCRAPYD_PROJECT_NAME: streamerbot
    ports:
      - 6800:6800
    volumes:
      - .:/home/spidercluster/streamerbot
    networks:
      - streamerbotnet
  mongo:
    container_name: mongo-streamerbot
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - streamerbotnet

networks:
  streamerbotnet:
    driver: bridge
